#!/bin/bash

set -euo pipefail  # Enable error checking

function show_help {
  echo "Usage: stod [Option] [.mkv, .mp4 or .mp3 ... or any 3 char format files]"
  echo ""
  echo "Options:"
  echo "  -h, --help       Show this help message"
  echo "  -v, --version    Show version information"
}

if [ $# -eq 0 ]; then
  show_help
  exit 1
fi

case $1 in
    -h|--help)
      show_help
      exit 1
      ;;
    -v|--version)
      echo "stod version 1.0"
      exit 1 
      ;;
esac

for name in "$@"; do
  if [[ "$name" == .*. ]]; then
    # Skip files with an extension
    continue
  fi

  extension="${name##*.}"
  new_name="${name%.*}"
  new_name="${new_name// /.}"
  new_name="$new_name.$extension"

  mv -n "$name" "$new_name"
done
